---
title: "Microglia example"
output: html_document
date: "2025-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 
```{r cars}
rm(list=ls())

small_data <- readRDS("C:/Users/WD/Downloads/MiGA_eQTL.chr2_ENSG00000151694.univariate_data.rds")

y= small_data$ENSG00000151694$residual_Y[[3]]
X= small_data$ENSG00000151694$residual_X[[3]]
res_susie =susieR::susie(X = X,y=y,L=20   )
res_susie$sets
```
 obvious overfitting
```{r }

plot(y , predict(res_susie , X) )

plot( res_susie$pip)
res_susie$sigma2/var(y)
```
 
 
 
 
 
 
```{r}
library(susieRsmall)

res_susie_small =susieRsmall::susie(X = X,y=y,L=10, max_iter = 20 , estimate_prior_method = "EM")
res_susie_small$sets
```
 
 
 
```{r}

h2_Gaussian = 100*(1-res_susie$sigma2/var(y))

h2_SS = 100*(1-res_susie_small$sigma2/var(y))
par(mfrow=c(1,2))
susie_plot( res_susie, y="PIP",
            main=paste( "SuSiE Gaussian SER "))

susie_plot( res_susie_small, y="PIP",
            main=paste( "SuSiE Servin Stephens SER "))
par(mfrow=c(1,1))
```









```{r}
plot( exp(res_susie_small$lbf_variable[1,])/sum(exp(res_susie_small$lbf_variable[1,])))
```
```{r}
plot( exp(res_susie_small$lbf_variable[4,])/sum(exp(res_susie_small$lbf_variable[4,])))
```






